// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfKQvWpDvfPP25trO5Mpj_6HD1kjIAOlY',
    appId: '1:181478177080:web:0dee4441b85f058007e9cd',
    messagingSenderId: '181478177080',
    projectId: 'sharedtabs-e11d5',
    authDomain: 'sharedtabs-e11d5.firebaseapp.com',
    storageBucket: 'sharedtabs-e11d5.firebasestorage.app',
    measurementId: 'G-HGEBZVR40S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc4JXqHtaGKQVxhicyxc755jf9RsCWvW4',
    appId: '1:181478177080:android:66b63821d6349cdd07e9cd',
    messagingSenderId: '181478177080',
    projectId: 'sharedtabs-e11d5',
    storageBucket: 'sharedtabs-e11d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNT-4JSw0xiOJ0a3JZBesyNYWHQoaotng',
    appId: '1:181478177080:ios:9ab8a94bd951e0da07e9cd',
    messagingSenderId: '181478177080',
    projectId: 'sharedtabs-e11d5',
    storageBucket: 'sharedtabs-e11d5.firebasestorage.app',
    iosBundleId: 'com.example.guitarSharedTabs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNT-4JSw0xiOJ0a3JZBesyNYWHQoaotng',
    appId: '1:181478177080:ios:9ab8a94bd951e0da07e9cd',
    messagingSenderId: '181478177080',
    projectId: 'sharedtabs-e11d5',
    storageBucket: 'sharedtabs-e11d5.firebasestorage.app',
    iosBundleId: 'com.example.guitarSharedTabs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfKQvWpDvfPP25trO5Mpj_6HD1kjIAOlY',
    appId: '1:181478177080:web:c3116e1a24666f3b07e9cd',
    messagingSenderId: '181478177080',
    projectId: 'sharedtabs-e11d5',
    authDomain: 'sharedtabs-e11d5.firebaseapp.com',
    storageBucket: 'sharedtabs-e11d5.firebasestorage.app',
    measurementId: 'G-13ECS1QEHW',
  );
}
